### ISSUE TITLE
Lag in menu

### ISSUE THREAD

**Issue by dvzrv** [Generator/Grub2-themes#1]
There seems to be a lag, when using the menu in the Archlinux theme.
I have about 6 Archlinux entries and one for Windows, using the Archlinux theme (which looks pretty, btw!).
When grub loads, the menu is quite unresponsive... veeeeeeeery slow. Any experience with that?

As my /boot/grub is on my /, I'm loading the theme from /usr/share/grub/themes/Archlinux/theme.txt and have skipped the part of copying all the files to my /boot/grub directory.
Should work the same, right? I mean... after all it's loading... it's just veeeeeery slow, switching from one menu entry to the next.
Maybe it's because of the icons?
I'll try copying the stuff to my /boot/grub directory later on... see if things change.

**Comment by Generator** [comment]
The lag isn't theme related, it's a grub problem

> **Keyboard lag**
> Many users will notice a lag in the time it takes to switch between menu items.  Extensive testing show 
> that it's caused by the time it takes to update the graphical elements of the boot_menu components.  

See "[The Definitive Guide To Theming GRUB 2 v1.99](https://docs.google.com/open?id=0B82343FTJphIbElHUGVac1hBZnc)" pag 73
