### ISSUE TITLE
Error message when selecting menu item

### ISSUE THREAD

**Issue by terminalmage** [Generator/Grub2-themes#2]
I get an error message (see [here](http://i.imgur.com/opJKdit.jpg)) when I select the menu item instead of waiting for it to timeout and boot the default.

**Comment by antiagainst** [comment]
I have the same error message here:
"requested to scale to a size w/ a zero dimension."
But the system can boot successfully. Just kind of anoying.

**Comment by yang-ling** [comment]
Me too. But the system can boot.

**Comment by Generator** [comment]
Sorry for the delay.
Post your resolutions of GRUB_GFXMODE
You can also try it with other resolutions or GRUB_GFXMODE=auto to see if the problem persist.
Never seen this error in my tests

Needs to be a framebuffer resolution see https://wiki.archlinux.org/index.php/Grub#Setting_the_framebuffer_resolution

**Comment by Generator** [comment]
It seems that removing the files progress_highlight_w.png progress_highlight_e.png solves the problem for now
`#rm /boot/grub/themes/Archxion/progress_highlight_{e,w}.png`

**Comment by yang-ling** [comment]
I have tried the new one from AUR. It works. Thanks.
