### ISSUE TITLE
Archxion - Error requested to scale to a size w/ a zero dimension

### ISSUE THREAD

**Issue by ghost** [Generator/Grub2-themes#4]
Hi,

First let me say these are really nice themes, thanks for creating these, and I hope if you have some free time in the future you might create some more for Arch...

I noticed when I'm using Archxion if I don't let it boot automatically and move the up and down keyboard arrows and let it sit for a few seconds, then later highlight the kernel I want to boot and press enter on the keyboard, when the window pops up to begin booting I get this message;

error requested to scale to a size w/ a zero dimension

If I just let it sit and boot automatically this message doesn't appear...

Here's a screen shot of the error message;

http://i.imgur.com/fys0xqI.jpg

**Comment by Generator** [comment]
See [#2](https://github.com/Generator/Grub2-themes/issues/2)
